figure('Position',[10 400 350 415]);
figure('Position',[375 400 430 415]);
figure('Position',[820 400 320 415]);

figure(1)
uicontrol(gcf,...
'Style','text',...
'Position',[10 390 220 20],...
'String','Channel Equalization 3');

uicontrol(gcf,...
'Style','text',...
'Position',[10 360 150 20],...
'String','edge frequency [norm.] =');
fg=uicontrol(gcf,...
'Style','edit',...
'Position',[165 360 30 20],...
'String','.2');
uicontrol(gcf,...
'Style','text',...
'Position',[205 360 60 20],...
'String','order =');
ordn=uicontrol(gcf,...
'Style','edit',...
'Position',[270 360 30 20],...
'String','10');
uicontrol(gcf,...
'Style','text',...
'Position',[10 330 50 20],...
'String','SB-att.=');
sniv=uicontrol(gcf,...
'Style','edit',...
'Position',[65 330 30 20],...
'String','.4');
kanal=uicontrol(gcf,...
'Style','pushbutton',...
'Position',[105 325 70 30],...
'String','Channel',...
'Value',0,...
'Callback',[...
'f=str2num(get(fg,''String''));',...
'K=str2num(get(ordn,''String''));',...
'sn=str2num(get(sniv,''String''));',...
'fax=[0:.1:1];',...
'Mag0=[ones(1,round(f*2*11)) sn*ones(1,11-round(f*2*11))];',...
'Mag1=[ones(1,round(f*2*11)) .5*sn*ones(1,11-round(f*2*11))];',...
'h0=fir2(K,fax,Mag0);',...
'h1=fir2(K,fax,Mag1);',...
'visa1(h0);']);

uicontrol(gcf,...
'Style','text',...
'Position',[10 290 130 20],...
'String','symbol interval [sample] =');
inte=uicontrol(gcf,...
'Style','text',...
'Position',[145 290 30 20],...
'String','5');
uicontrol(gcf,...
'Style','text',...
'Position',[185 290 70 20],...
'String','window =');
sigint=uicontrol(gcf,...
'Style','edit',...
'Position',[260 290 30 20],...
'String','40');
inteval=uicontrol(gcf,...
'Style','slider',...
'Min',1,...
'Max',10,...
'Value',5,...
'Position',[10 265 170 20],...
'Callback',[...
'figure(2);',...
'N=round(get(inteval,''Value''));',...
'set(inte,''String'',num2str(N));']);

uicontrol(gcf,...
'Style','text',...
'Position',[10 240 70 20],...
'String','noise variance =');
vari=uicontrol(gcf,...
'Style','edit',...
'Position',[85 240 40 20],...
'String','.0005');

uicontrol(gcf,...
'Style','text',...
'Position',[10 200 30 20],...
'String','mu=');
adk=uicontrol(gcf,...
'Style','text',...
'Position',[45 200 30 20],...
'String','.5');
adkonst=uicontrol(gcf,...
'Style','slider',...
'Min',0,...
'Max',3,...
'Value',.5,...
'Position',[80 200 170 20],...
'Callback',[...
'figure(2);',...
'mu=get(adkonst,''Value'');',...
'set(adk,''String'',num2str(mu));']);

uicontrol(gcf,...
'Style','text',...
'Position',[10 170 60 20],...
'String','equ. order =');
adordn=uicontrol(gcf,...
'Style','edit',...
'Position',[75 170 30 20],...
'String','10');

uicontrol(gcf,...
'Style','text',...
'Position',[115 170 70 20],...
'String','update =');
udati=uicontrol(gcf,...
'Style','edit',...
'Position',[190 170 30 20],...
'String','6');

uicontrol(gcf,...
'Style','text',...
'Position',[10 140 50 20],...
'String','delay =');
delej=uicontrol(gcf,...
'Style','edit',...
'Position',[65 140 30 20],...
'String','10');

uicontrol(gcf,...
'Style','pushbutton',...
'Position',[10 100 50 25],...
'String','START',...
'Callback',[...
'q=length(h0);',...
'p=str2num(get(adordn,''String''));',...
'br=str2num(get(vari,''String''));',...
'S=str2num(get(udati,''String''));',...
'del=str2num(get(delej,''String''));',...
'M=str2num(get(sigint,''String''));',...
'w=zeros(1,p);',...
'x=zeros(M,1);',...
'y=zeros(M,1);',...
'xh=zeros(M,1);',...
't=1;',...
'set(stop,''Value'',0);',...
'st=0;',...
'drift=0;',...
'while st==0;',...
'  N=round(get(inteval,''Value''));',...
'  mu=get(adkonst,''Value'');',...
'  df=get(modpop,''Value'');',...
'  dr=get(drpop,''Value'');',...
'  x=[0; x(1:length(x)-1)];',...
'  if mod(t,N)==0;',...
'    x(1)=2*round(rand)-1;',...
'  end;',...
'  y(2:length(y))=y(1:length(y)-1);',...
'  if dr==1;',...
'    h=h0;',...
'    y(1)=h*x(1:q)+sqrt(br)*randn;',...
'  elseif dr==2;',...
'    h=(1-drift)*h0+drift*h1;',...
'    y(1)=h*x(1:q)+sqrt(br)*randn;',...
'    drift=min(1,drift+.01);',...
'  end;',...
'  xh(2:M)=xh(1:M-1);',...
'  xh(1)=w*y(1:p);',...
'  if df==1;',...
'    d=x(1+del);',...
'  elseif df==2;',...
'    if mod(t+del,N)==0;',...
'      d=sign(xh(1));',...
'    else;',...
'      d=0;',...
'    end;',...
'  elseif df==3;',...
'    d=0;',...
'    mu=0;',...
'  end;',...
'  w=w+mu*( d-xh(1) )*rot90(y(1:p));',...
'  if mod(t,S)==0;',...
'    visa1(h);',...
'    visaw3(w,x,y,xh,p,h,N,br);',...
'    pause(.1);',...
'  end;',...
'  t=t+1;',...
'  st=get(stop,''Value'');',...
'end;';]);

modpop=uicontrol(gcf,...
'Style','popup',...
'Position',[10 70 120 25],...
'String','training|decision feedback|freeze',...
'Callback','figure(3);');

drpop=uicontrol(gcf,...
'Style','popup',...
'Position',[140 70 100 25],...
'String','fixed|drift',...
'Callback','figure(3);');

stop=uicontrol(gcf,...
'Style','checkbox',...
'Position',[70 100 60 25],...
'Value',0,...
'String','STOP',...
'Callback',[...
'figure(3);',...
'subplot(222);',...
'set(stop,''Value'',1);';]);

uicontrol(figure(1),...
'Style','pushbutton',...
'String','EXIT',...
'Position',[275 40 70 30],...
'Callback',[...
'close;',...
'close;',...
'close;']);

